#pragma config(Sensor, in1,    leftLight,      sensorLineFollower)
#pragma config(Sensor, in2,    middleLight,    sensorLineFollower)
#pragma config(Sensor, in3,    rightLight,     sensorLineFollower)
#pragma config(Sensor, in4,    wristPot,       sensorPotentiometer)
#pragma config(Sensor, in6,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  extensionEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl11, armEncoder,     sensorQuadEncoder)
#pragma config(Motor,  port1,           frontRightMotor, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rearRightMotor, tmotorVex393_MC29, openLoop, reversed, encoderPort, dgtl1)
#pragma config(Motor,  port3,           frontLeftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rearLeftMotor, tmotorVex393_MC29, openLoop, encoderPort, dgtl3)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop, encoderPort, dgtl11)
#pragma config(Motor,  port8,           leftExtendMotor, tmotorVex393_MC29, openLoop, encoderPort, dgtl5)
#pragma config(Motor,  port9,           rightExtendMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          wristMotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void liftArm(int time, int speed)
{
	clearTimer(T2);
	while(time1[T2] < time)
	{
		motor[armMotor] = speed;
	}
	motor[armMotor] = 0;
}

void moveForward(int time, int speed){
	clearTimer(T1);
	while(time1[T1] < time)
	{
		motor[rearRightMotor] = speed;
		motor[frontRightMotor] = speed;
		motor[rearLeftMotor] = speed;
		motor[frontLeftMotor] = speed;
	}
	//Stop the robot
	motor[rearRightMotor] = 0;
	motor[frontRightMotor] = 0;
	motor[rearLeftMotor] = 0;
	motor[frontLeftMotor] = 0;
}

void turnRight(int time, int speed)
{
	clearTimer(T1);
	while(time1[T1] < time)
	{
		motor[rearRightMotor] = -speed;
		motor[frontRightMotor] = -speed;
		motor[rearLeftMotor] = speed;
		motor[frontLeftMotor] = speed;
	}
	//Stop the robot
	motor[rearRightMotor] = 0;
	motor[frontRightMotor] = 0;
	motor[rearLeftMotor] = 0;
	motor[frontLeftMotor] = 0;
}

void turnLeft(int time, int speed)
{
	clearTimer(T1);
	while(time1[T1] < time)
	{
		motor[rearRightMotor] = speed;
		motor[frontRightMotor] = speed;
		motor[rearLeftMotor] = -speed;
		motor[frontLeftMotor] = -speed;
	}
	//Stop the robot
	motor[rearRightMotor] = 0;
	motor[frontRightMotor] = 0;
	motor[rearLeftMotor] = 0;
	motor[frontLeftMotor] = 0;
}

void openClaw(int time, int speed)
{
	clearTimer(T3);
	while(time1[T3] < time)
	{
		motor[clawMotor] = -speed;
	}
	//Stop the Claw
	motor[clawMotor] = 0;
}

void closeClaw(int time, int speed)
{
	clearTimer(T3);
	while(time1[T3] < time)
	{
		motor[clawMotor] = speed;
	}
	//Stop the Claw
	motor[clawMotor] = 0;
}

void extendLeft(int time, int speed)
{
	clearTimer(T3);
	while(time1[T3] < time)
	{
		motor[leftExtendMotor] = speed;
	}
	//Stop the Claw
	motor[leftExtendMotor] = 0;
}

void retractLeft(int time, int speed)
{
	clearTimer(T3);
	while(time1[T3] < time)
	{
		motor[leftExtendMotor] = -speed;
	}
	//Stop the Claw
	motor[leftExtendMotor] = 0;
}

void extendRight(int time, int speed)
{
	clearTimer(T3);
	while(time1[T3] < time)
	{
		motor[rightExtendMotor] = speed;
	}
	//Stop the Claw
	motor[rightExtendMotor] = 0;
}

void retractRight(int time, int speed)
{
	clearTimer(T3);
	while(time1[T3] < time)
	{
		motor[rightExtendMotor] = -speed;
	}
	//Stop the Claw
	motor[rightExtendMotor] = 0;
}

task main()
{
	//Sample Task
	liftArm(1000, 100);
	extendLeft(2000, 100);
	extendRight(2000, 100);
	wait1Msec(500);

	openClaw(1000, 100);
	wait1Msec(500);

	closeClaw(1000, 100);
	wait1Msec(500);

	moveForward(3000, 100);
	wait1Msec(500);

	turnRight(3000, 100);
	wait1Msec(500);

	turnLeft(3000, 100);
	wait1Msec(500);


}
