#pragma config(Motor,  port1,           rearLeftWheelMotor, tmotorVex269_HBridge, openLoop)
#pragma config(Motor,  port2,           rearRightWheelMotor, tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           frontLeftWheelMotor, tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port4,           frontRightWheelMotor, tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port5,           leftArmMotor,  tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port6,           rightArmMotor, tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port7,           wristMotor,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port8,           clawMotor,     tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
////////////////////////////////////////////////////////////////////////////////////
//
//									AdvancedFunctions
//
//	These functions are based upon the functions found in the included 'BaseFunctions.c'
//  file.
//
//	List of Functions:
//
//	NOTE: Motors must be configured to match given aliases.
////////////////////////////////////////////////////////////////////////////////////
*/

#include "BaseFunctions.c"

void turnRight45()
{
	turnRight(2000, 50);
}

void turnLeft45()
{
	turnLeft(2000, 50);
}

void turnRight90()
{

}

void turnLeft90()
{

}

void turn180()
{

}

void extendArmFull()
{

}












task main()
{



}
